In [2]:
from sklearn import preprocessing

In [3]:
import pandas as pd

### scale numeric columns in train data

In [4]:
raw_train = pd.read_csv('./data/train.csv')

In [6]:
raw_train.describe()

,id,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
count,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000,188318.000000
mean,294135.982561,0.493861,0.507188,0.498918,0.491812,0.487428,0.490945,0.484970,0.486437,0.485506,0.498066,0.493511,0.493150,0.493138,0.495717,3037.337686
std,169336.084867,0.187640,0.207202,0.202105,0.211292,0.209027,0.205273,0.178450,0.199370,0.181660,0.185877,0.209737,0.209427,0.212777,0.222488,2904.086186
min,1.000000,0.000016,0.001149,0.002634,0.176921,0.281143,0.012683,0.069503,0.236880,0.000080,0.000000,0.035321,0.036232,0.000228,0.179722,0.670000
25%,147748.250000,0.346090,0.358319,0.336963,0.327354,0.281143,0.336105,0.350175,0.312800,0.358970,0.364580,0.310961,0.311661,0.315758,0.294610,1204.460000
50%,294539.500000,0.475784,0.555782,0.527991,0.452887,0.422268,0.440945,0.438285,0.441060,0.441450,0.461190,0.457203,0.462286,0.363547,0.407403,2115.570000
75%,440680.500000,0.623912,0.681761,0.634224,0.652072,0.643315,0.655021,0.591045,0.623580,0.566820,0.614590,0.678924,0.675759,0.689974,0.724623,3864.045000
max,587633.000000,0.984975,0.862654,0.944251,0.954297,0.983674,0.997162,1.000000,0.980200,0.995400,0.994980,0.998742,0.998484,0.988494,0.844848,121012.250000

In [29]:
col_num_name = map(lambda x:'cont'+str(x+1),range(14))
col_num_name.insert(0,'loss')
train_scale_num = preprocessing.scale(raw_train.loc[:,col_num_name])

In [30]:
train_scale_num = pd.DataFrame(train_scale_num)
train_scale_num.columns = col_num_name
train_scale_num.describe()

,loss,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14
count,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05,1.883180e+05
mean,1.463992e-16,-3.758267e-16,-3.509514e-16,-9.964080e-17,7.236724e-16,-1.284134e-15,7.627087e-17,-1.060934e-16,8.138601e-16,-7.618786e-16,6.765405e-17,3.541173e-16,-6.840749e-16,-1.078136e-15,-2.819567e-16
std,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00
min,-1.045656e+00,-2.631881e+00,-2.442261e+00,-2.455589e+00,-1.490316e+00,-9.868842e-01,-2.329891e+00,-2.328204e+00,-1.251730e+00,-2.672174e+00,-2.679556e+00,-2.184604e+00,-2.181765e+00,-2.316558e+00,-1.420286e+00
25%,-6.311392e-01,-7.875273e-01,-7.184773e-01,-8.013468e-01,-7.783474e-01,-9.868842e-01,-7.543139e-01,-7.553681e-01,-8.709303e-01,-6.965570e-01,-7.181437e-01,-8.703801e-01,-8.666038e-01,-8.336422e-01,-9.039048e-01
50%,-3.174045e-01,-9.634084e-02,2.345240e-01,1.438494e-01,-1.842255e-01,-3.117298e-01,-2.435770e-01,-2.616155e-01,-2.276036e-01,-2.425212e-01,-1.983893e-01,-1.731129e-01,-1.473762e-01,-6.090452e-01,-3.969402e-01
75%,2.846711e-01,6.930871e-01,8.425272e-01,6.694845e-01,7.584762e-01,7.457784e-01,7.993124e-01,5.944241e-01,6.878805e-01,4.476154e-01,6.268911e-01,8.840306e-01,8.719477e-01,9.250844e-01,1.028851e+00
max,4.062387e+01,2.617323e+00,1.715558e+00,2.203481e+00,2.188845e+00,2.374086e+00,2.466081e+00,2.886134e+00,2.476616e+00,2.806862e+00,2.673360e+00,2.408891e+00,2.412945e+00,2.328058e+00,1.569220e+00

In [36]:
x = raw_train[raw_train.columns[map(lambda i:i not in col_num_name,raw_train.columns)]]
x.head()

,id,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cat107,cat108,cat109,cat110,cat111,cat112,cat113,cat114,cat115,cat116
0,1,A,B,A,B,A,A,A,A,B,...,J,G,BU,BC,C,AS,S,A,O,LB
1,2,A,B,A,A,A,A,A,A,B,...,K,K,BI,CQ,A,AV,BM,A,O,DP
2,5,A,B,A,A,B,A,A,A,B,...,F,A,AB,DK,A,C,AF,A,I,GK
3,10,B,B,A,B,A,A,A,A,B,...,K,K,BI,CS,C,N,AE,A,O,DJ
4,11,A,B,A,B,A,A,A,A,B,...,G,B,H,C,C,Y,BM,A,K,CK

In [39]:
train_scale = pd.concat([train_scale_num.reset_index(drop=True),
                         x.reset_index(drop=True)],axis=1)
train_scale.head()

,loss,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,...,cat107,cat108,cat109,cat110,cat111,cat112,cat113,cat114,cat115,cat116
0,-0.283793,1.238750,-1.260936,-1.540471,1.409553,-0.848538,1.107908,-0.840070,-0.922092,1.023032,...,J,G,BU,BC,C,AS,S,A,O,LB
1,-0.603888,-0.870537,1.109451,0.463932,0.578923,1.906010,-0.253457,-0.271142,0.573972,-0.738944,...,K,K,BI,CQ,A,AV,BM,A,O,DP
2,-0.011104,-1.236521,-0.718477,-0.072846,-1.206334,-0.432284,-0.980633,-0.949428,-1.069556,-1.237183,...,F,A,AB,DK,A,C,AF,A,I,GK
3,-0.722256,-0.918075,0.234524,0.143849,-0.558452,-0.311730,-0.243577,-0.525875,-0.845049,-0.904033,...,K,K,BI,CS,C,N,AE,A,O,DJ
4,-0.094174,-1.175963,-1.675658,0.143849,-0.088079,1.037383,-1.523596,-1.331256,-1.207792,-1.456660,...,G,B,H,C,C,Y,BM,A,K,CK

In [40]:
train_scale.to_csv('./output/raw_train_scale.csv')

### scale numeric data in test data

In [41]:
raw_test = pd.read_csv('./data/test.csv')

In [42]:
col_num_name = map(lambda x:'cont'+str(x+1),range(14))
test_scale_num = preprocessing.scale(raw_test.loc[:,col_num_name])

In [43]:
test_scale_num = pd.DataFrame(test_scale_num)
test_scale_num.columns = col_num_name
test_scale_num.describe()

,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14
count,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05,1.255460e+05
mean,-1.909848e-16,1.231371e-15,6.033041e-16,9.163067e-16,1.125206e-15,2.233269e-16,3.141832e-16,-1.313350e-16,1.731526e-16,5.606031e-17,4.121371e-16,-1.043634e-16,-3.098678e-16,-6.587268e-17
std,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00
min,-2.630510e+00,-2.445369e+00,-2.456662e+00,-1.496164e+00,-9.874651e-01,-2.332529e+00,-2.331056e+00,-1.255437e+00,-2.668021e+00,-2.683042e+00,-2.181766e+00,-2.178478e+00,-2.322109e+00,-1.424083e+00
25%,-7.823155e-01,-7.185414e-01,-7.994805e-01,-7.825839e-01,-9.874651e-01,-7.592589e-01,-7.492760e-01,-8.491204e-01,-6.975401e-01,-7.223973e-01,-8.716760e-01,-8.364793e-01,-8.414911e-01,-9.021707e-01
50%,-9.929338e-02,2.361431e-01,1.473951e-01,-1.871170e-01,-3.126068e-01,-2.464485e-01,-2.633746e-01,-2.322283e-01,-2.446847e-01,-1.731070e-01,-1.766020e-01,-1.510686e-01,-6.172422e-01,-4.019639e-01
75%,7.032488e-01,8.452201e-01,6.739641e-01,7.577188e-01,7.444376e-01,8.127175e-01,5.896426e-01,7.104989e-01,4.550229e-01,6.503444e-01,8.772165e-01,8.964221e-01,9.145100e-01,1.029617e+00
max,2.609743e+00,1.719793e+00,2.210686e+00,2.199622e+00,2.369319e+00,2.456420e+00,2.877453e+00,2.482598e+00,2.796771e+00,2.667779e+00,2.392946e+00,2.395387e+00,2.315309e+00,1.568775e+00

In [44]:
x = raw_test[raw_test.columns[map(lambda i:i not in col_num_name,
                                  raw_test.columns)]]
test_scale = pd.concat([test_scale_num.reset_index(drop=True),
                         x.reset_index(drop=True)],axis=1)
test_scale.head()

,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,...,cat107,cat108,cat109,cat110,cat111,cat112,cat113,cat114,cat115,cat116
0,-0.919627,-1.004841,-1.245845,-0.424126,-0.987465,-0.124516,-0.941866,0.625858,-0.781654,-0.638611,...,L,K,BI,BC,A,J,AX,A,Q,HG
1,0.746364,0.550513,0.773525,2.154891,1.667974,-0.047492,-0.236131,1.132050,0.180553,0.565214,...,F,B,BI,CO,E,G,X,A,L,HK
2,-1.083390,1.112616,1.055311,-0.377322,1.104120,-1.361463,-0.896536,-0.951251,-0.781654,-1.041248,...,G,A,BI,CS,C,U,AE,A,K,CK
3,-1.201452,0.845220,0.468046,-0.651952,-0.433108,-0.594719,-0.803751,-0.436589,-0.843587,-0.990105,...,K,K,BI,CR,A,AY,AJ,A,P,DJ
4,0.316018,-1.004841,-1.163270,0.970233,-0.884485,-0.453981,-0.526796,-1.255437,-0.267415,0.035767,...,E,B,AB,EG,A,E,I,C,J,HA

In [45]:
test_scale.to_csv('./output/raw_test_scale.csv')